esphome:
  name: gas-meter
  friendly_name: 燃气表
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: Mijia
  password: 09081005
  fast_connect: true
  ap:
    ssid: "Gas‑Monitor‑AP"
    password: "12345678"

ota:
  - platform: esphome
    password: "12345678"
  - platform: web_server

api:
  encryption:
    key: n9T7BhS1RWNqfdsrCVUcufHXapo9/oc+Q5jlfN9qQPI=
  reboot_timeout: 0s

web_server:
  port: 80

logger:
  level: INFO

sensor:
  # 脉冲计数：1脉冲 = 0.01m³
  - platform: pulse_counter
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    name: "燃气总用量01"
    unit_of_measurement: "m³"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    total:
      name: "燃气累计总量02"
      id: gas_total
      unit_of_measurement: "m³"
      accuracy_decimals: 2

  # 瞬时流量 m³/min
  - platform: template
    name: "燃气瞬时流量"
    unit_of_measurement: "m³/min"
    accuracy_decimals: 3
    lambda: |-
      static float last_total = 0;
      static unsigned long last_time = millis();
      float now_total = id(gas_total).state;
      unsigned long now_t = millis();
      float delta = now_total - last_total;
      float flow = delta / ((now_t - last_time)/60000.0);
      last_total = now_total;
      last_time = now_t;
      return flow;

binary_sensor:
  - platform: status
    name: "燃气板状态"

button:
  - platform: restart
    name: "燃气板重启"
